language: php

notifications:
  email: false

php:
  - "7.4"
  - "8.0"

services:
  - mysql

install:
  - composer install  --no-plugins

before_script:
  - cp tests/testData/source/config.inc.php.dist tests/testData/source/config.inc.php

script:
  - vendor/bin/phpunit tests
