language: php

notifications:
  email: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

install:
  - composer install

script:
  - vendor/bin/phpunit tests

services:
  - mysql

before_script:
  - cp tests/testData/source/config.inc.php.dist tests/testData/source/config.inc.php
